tests/files_geojson/feature.geojson, tests/files_geojson/feature_collection.geojson, tests/files_topojson/geometry_collection.topojson, tests/test_extract.py, tests/test_hashmap.py, topojson/extract.py, topojson/utils/dummy.py
=> improve parsing feature collection and feature

tests/test_dedup.py, topojson/dedup.py, topojson/hashmap.py
This PR assigns fix https://github.com/mattijn/topojson/issues/3
by initiating 'array_bk_sarcs' as None.
=> solved unboundlocalerror array_bk_sarcs

tests/test_extract.py, topojson/extract.py
This PR address the direct serialization of shapely `GeometryCollection`
=> Fix https://github.com/mattijn/topojson/issues/13

README.md, docs/3-installation.md, docs/4-example-usage.md, docs/5-how-it-works.md, pyproject.toml, tests/test_extract.py, topojson/__init__.py, topojson/core/extract.py
fix https://github.com/mattijn/topojson/issues/21
=> include list as accepted type

topojson/core/cut.py, topojson/core/dedup.py, topojson/core/extract.py, topojson/core/hashmap.py, topojson/core/join.py, topojson/core/topology.py
fix https://github.com/mattijn/topojson/issues/46
=> changes the to_dict() functions

README.md, topojson/__init__.py
- fix linemerging of non-duplicate arcs #50
- include `__geo_interface__` attributed as input #53
- include travis testing on GitHub (thanks @Casyfill!)
- migrate from unittests to pytest (thanks @Casyfill!)
=> Version 1.0rc6

tests/test_topology.py, topojson/ops.py
Tests did not catch the error that during quantization a geometry.LineString cannot be reduced till 1 coordinate.
This PR add a test and fix the issue.
=> For ls cannot filter until 1 coordinate

README.md, topojson/__init__.py
This PR updates  `__init__.py` to version 1.0 and reflect this in the readme.
=> update version to 1.0

docs/api/topojson.core.topology.md, docs/example/input-types.md, tests/test_topology.py, topojson/core/hashmap.py, topojson/core/topology.py, topojson/utils.py
This PR renames the newly introduced argument `objects_name` into `object_name`.
=> rename objects_name to object_name

recipe/meta.yaml
Fix license to be conform SPDX
=> Add conda recipe

README.md, docs/installation.md
Once https://github.com/conda-forge/staged-recipes/pull/16117 is accepted and https://anaconda.org/conda-forge/topojson is online this PR can be accepted
=> update docs to include conda-forge install

tests/test_extract.py
add one test to check if properties are still included after applying a topology
=> add test to keep properties

.github/workflows/test.yml
Github Action will now test against:
```yml
shapely-version: ["1.8.0", "1.8.4", "2.0a1"]
```
=> Include shapely in matrix GitHub action workflow

pyproject.toml
This PR set the shapely version to `>= 1.8.0` (from `1.7a2`)
=> Set dependency shapely to version >= 1.8.0

topojson/ops.py
This PR intend to fix https://github.com/mattijn/topojson/issues/170
=> update strtree functions

topojson/core/extract.py, topojson/core/topology.py, topojson/ops.py
This PR introduce GeometryTypeError for parsing dicts during extraction.
=> Replaced ShapelyError with GeometryTypeError

tests/test_cut.py, tests/test_dedup.py, tests/test_topology.py, topojson/core/cut.py, topojson/ops.py
=> Fix find duplicates for rings

docs/api/topojson.core.join.md, docs/api/topojson.core.topology.md, docs/example/settings-tuning.md, tests/test_topology.py, topojson/core/join.py, topojson/core/topology.py, topojson/ops.py
This PR changes the quantize default from `1e6` to `1e5`.
=> change quantize default from `1e6` to `1e5`

README.md
=> add shapely 1 & 2 compliant badge

topojson/core/dedup.py, topojson/ops.py
Reverts mattijn/topojson#226
tests don’t pass
=> Revert "Replace `np.in1d` by `np.isin`"
